name: Run Task on Self-Hosted Runner

on:
  push:
    branches:
      - main  # or the name of your default branch
    paths:
      - 'databases.json'  # Trigger the workflow when this file changes

jobs:
  run_task:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/codeqluser/github-workflow-test
        shell: bash

    steps:
    - name: Run a script
      run: |
        echo "Running task on self-hosted runner"
        # Replace the following line with the actual task you want to run
        python3 scripts/hello.py
